services:
  astro:
    container_name: fixable-astro
    build:
      context: ./site
      target: dev-test
    restart: always
    ports:
      - 4323:4323
      - 4324:4324
    volumes:
      - '.:/fixable'
